seed = 0
parent_dir = "exp/adult/tdce_test"
real_data_path = "data/adult"
model_type = "mlp"
num_numerical_features = 4
device = "cuda:0"

[model_params]
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [256, 512]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"
scheduler = "cosine"
use_gumbel_softmax = true
tau_init = 1.0
tau_final = 0.3
tau_schedule = "anneal"

[train.main]
steps = 5000
lr = 0.0002
weight_decay = 1e-4
batch_size = 1024

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"

